### ISSUE TITLE
Compare our changes to the official ones

### ISSUE THREAD

**Issue by SolalPirelli** [PolyProg/domjudge#1]
Look at the diff from all of our commits, then look at what the official repo added/changed in the meantime. We'll decide what to do once we have that info.

**Comment by zommerfelds** [comment]
That seems like a good amount of work! https://github.com/DOMjudge/domjudge/compare/master...PolyProg:master
Good luck!

**Comment by eldering** [comment]
Hi all,

Let us know (via team@domjudge.org or the emaillist) if there's anything we can help with. Given that your fork is based on version 3.4, it might be easier to cherry-pick things, depending on what your intentions are.

**Comment by SolalPirelli** [comment]
This is done (at least it'll be when my open PR gets approved) - turns out most of our changes were hacking in stuff that later versions supported out-of-the-box.
